#!/usr/bin/env python3
"""Verify AIE x86 simulation output against golden expected output.

Reads the PLIO output text file from x86simulator and compares byte-by-byte
against the expected output generated by gen_plio_data.py.

Usage:
    python3 verify_x86sim.py \
        --sim-output build_x86/x86simulator_output/data/out_3x3.txt \
        --expected   data/expected_out.txt \
        --tile-meta  data/tile_meta.json
"""

import argparse
import json
import sys
import numpy as np


def read_plio_txt(filepath):
    """Read a PLIO text file (one or more integers per line) into a numpy array."""
    values = []
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if line:
                for tok in line.split():
                    values.append(int(tok))
    return np.array(values, dtype=np.int64)


def main():
    p = argparse.ArgumentParser(description="Verify AIE x86sim output")
    p.add_argument("--sim-output", required=True,
                   help="Path to simulation output text file")
    p.add_argument("--expected", required=True,
                   help="Path to expected output text file")
    p.add_argument("--tile-meta", default=None,
                   help="Path to tile_meta.json for context")
    p.add_argument("--max-errors", type=int, default=20,
                   help="Max mismatches to print")
    args = p.parse_args()

    # Load tile metadata if available
    if args.tile_meta:
        with open(args.tile_meta) as f:
            meta = json.load(f)
        print(f"Layer: [{meta['layer_index']}] {meta['layer_name']}")
        print(f"Kernel type: {meta['kernel_type']}")
        print(f"Output tile shape: {meta['out_shape']}")
    else:
        meta = None

    # Read both files
    sim_vals = read_plio_txt(args.sim_output)
    exp_vals = read_plio_txt(args.expected)

    print(f"\nSimulation output: {len(sim_vals)} values")
    print(f"Expected output:   {len(exp_vals)} values")

    if len(sim_vals) != len(exp_vals):
        print(f"\n  ERROR: Length mismatch! sim={len(sim_vals)} vs expected={len(exp_vals)}")
        # Still compare the overlapping portion
        min_len = min(len(sim_vals), len(exp_vals))
        sim_vals = sim_vals[:min_len]
        exp_vals = exp_vals[:min_len]
        print(f"  Comparing first {min_len} values...\n")

    # Compare
    sim_i8 = np.clip(sim_vals, -128, 127).astype(np.int8)
    exp_i8 = np.clip(exp_vals, -128, 127).astype(np.int8)

    mismatches = np.where(sim_i8 != exp_i8)[0]
    total = len(sim_i8)
    n_match = total - len(mismatches)

    print(f"\nResults:")
    print(f"  Total values:  {total}")
    print(f"  Matching:      {n_match} ({100.0 * n_match / total:.2f}%)")
    print(f"  Mismatches:    {len(mismatches)}")

    if len(mismatches) == 0:
        print(f"\n  ✅ PASS — Bit-exact match!")
        return 0

    # Report mismatches
    print(f"\n  ❌ FAIL — {len(mismatches)} mismatches")
    n_show = min(len(mismatches), args.max_errors)
    print(f"\n  First {n_show} mismatches:")
    print(f"  {'Index':>8s}  {'Sim':>6s}  {'Expected':>8s}  {'Diff':>6s}")
    print(f"  {'-'*8}  {'-'*6}  {'-'*8}  {'-'*6}")

    for i in range(n_show):
        idx = mismatches[i]
        s = int(sim_i8[idx])
        e = int(exp_i8[idx])
        d = s - e
        print(f"  {idx:8d}  {s:6d}  {e:8d}  {d:+6d}")

    # Statistics
    diffs = sim_i8[mismatches].astype(np.int16) - exp_i8[mismatches].astype(np.int16)
    print(f"\n  Mismatch statistics:")
    print(f"    Max abs diff: {np.max(np.abs(diffs))}")
    print(f"    Mean abs diff: {np.mean(np.abs(diffs)):.2f}")
    print(f"    Off by 1 count: {np.sum(np.abs(diffs) == 1)} "
          f"({100.0 * np.sum(np.abs(diffs) == 1) / len(mismatches):.1f}% of mismatches)")

    return 1


if __name__ == "__main__":
    sys.exit(main())
