// Unit test harness: compares the scalar INT8 conv kernel output to the
// golden .i8.bin generated by fpga/generate_golden_int8.py.
//
// Usage (one layer):
//   ./test_layer \
//       --input   layer_02_input.i8.bin \
//       --weight  backbone_enc1_residual_0_conv1.weight.int8.bin \
//       --bias    layer_02_bias.i32.bin \
//       --mult    backbone_enc1_residual_0_conv1.requant_mult.bin \
//       --shift   backbone_enc1_residual_0_conv1.requant_shift.bin \
//       --expected layer_02_output.i8.bin \
//       --IC 32 --H 256 --W 2048 \
//       --OC 32 --KH 1 --KW 1 \
//       --stride-h 1 --stride-w 1 \
//       --pad-h 0 --pad-w 0 \
//       --op Conv [--lrelu]
//
// Exit code: 0 = PASS, 1 = data mismatch, 2 = I/O or shape error.

#include "conv_scalar.hpp"

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>
#include <cstdlib>

static std::vector<uint8_t> read_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        std::cerr << "ERROR: failed to open " << path << std::endl;
        std::exit(2);
    }
    return std::vector<uint8_t>((std::istreambuf_iterator<char>(f)),
                                 std::istreambuf_iterator<char>());
}

static std::string get_str(int argc, char** argv, const std::string& name,
                           const char* def = nullptr) {
    for (int i = 1; i + 1 < argc; ++i) {
        if (name == argv[i]) return argv[i + 1];
    }
    if (def) return def;
    std::cerr << "ERROR: missing required arg " << name << std::endl;
    std::exit(2);
}

static int get_int(int argc, char** argv, const std::string& name, int def = -1) {
    for (int i = 1; i + 1 < argc; ++i) {
        if (name == argv[i]) return std::atoi(argv[i + 1]);
    }
    if (def >= 0) return def;
    std::cerr << "ERROR: missing required arg " << name << std::endl;
    std::exit(2);
}

static bool get_flag(int argc, char** argv, const std::string& name) {
    for (int i = 1; i < argc; ++i) {
        if (name == argv[i]) return true;
    }
    return false;
}

int main(int argc, char** argv) {
    const std::string input_f    = get_str(argc, argv, "--input");
    const std::string weight_f   = get_str(argc, argv, "--weight");
    const std::string bias_f     = get_str(argc, argv, "--bias");
    const std::string mult_f     = get_str(argc, argv, "--mult");
    const std::string shift_f    = get_str(argc, argv, "--shift");
    const std::string expected_f = get_str(argc, argv, "--expected");

    const int IC = get_int(argc, argv, "--IC");
    const int H  = get_int(argc, argv, "--H");
    const int W  = get_int(argc, argv, "--W");
    const int OC = get_int(argc, argv, "--OC");
    const int KH = get_int(argc, argv, "--KH");
    const int KW = get_int(argc, argv, "--KW");

    const int stride_h  = get_int(argc, argv, "--stride-h", 1);
    const int stride_w  = get_int(argc, argv, "--stride-w", 1);
    const int pad_h     = get_int(argc, argv, "--pad-h", 0);
    const int pad_w     = get_int(argc, argv, "--pad-w", 0);
    const int out_pad_h = get_int(argc, argv, "--out-pad-h", 0);
    const int out_pad_w = get_int(argc, argv, "--out-pad-w", 0);

    const std::string op = get_str(argc, argv, "--op", "Conv");
    const bool has_lrelu = get_flag(argc, argv, "--lrelu");
    const bool verbose   = get_flag(argc, argv, "--verbose");
    const int  dump_n    = get_int(argc, argv, "--dump-n", 0);

    const bool is_transpose = (op == "ConvTranspose");

    // ---- Load all binaries
    auto in_buf  = read_file(input_f);
    auto wt_buf  = read_file(weight_f);
    auto bs_buf  = read_file(bias_f);
    auto mu_buf  = read_file(mult_f);
    auto sh_buf  = read_file(shift_f);
    auto ex_buf  = read_file(expected_f);

    // ---- Sanity checks on sizes
    const size_t expected_in_bytes  = (size_t)IC * H * W;
    const size_t expected_wt_bytes  = (size_t)OC * IC * KH * KW;
    const size_t expected_bias_bytes = (size_t)OC * sizeof(int32_t);
    const size_t expected_mult_bytes = (size_t)OC * sizeof(int32_t);
    const size_t expected_shift_bytes = (size_t)OC;

    if (in_buf.size() != expected_in_bytes) {
        std::cerr << "ERROR: input size " << in_buf.size() << " != expected "
                  << expected_in_bytes << " (IC*H*W)\n";
        return 2;
    }
    if (wt_buf.size() != expected_wt_bytes) {
        std::cerr << "ERROR: weight size " << wt_buf.size() << " != expected "
                  << expected_wt_bytes << " (OC*IC*KH*KW)\n";
        return 2;
    }
    if (bs_buf.size() != expected_bias_bytes) {
        std::cerr << "ERROR: bias size " << bs_buf.size() << " != expected "
                  << expected_bias_bytes << " (OC*4)\n";
        return 2;
    }
    if (mu_buf.size() != expected_mult_bytes) {
        std::cerr << "ERROR: mult size " << mu_buf.size() << " != expected "
                  << expected_mult_bytes << " (OC*4)\n";
        return 2;
    }
    if (sh_buf.size() != expected_shift_bytes) {
        std::cerr << "ERROR: shift size " << sh_buf.size() << " != expected "
                  << expected_shift_bytes << " (OC)\n";
        return 2;
    }

    const int8_t*  in_i8    = (const int8_t*)in_buf.data();
    const int8_t*  w_i8     = (const int8_t*)wt_buf.data();
    const int32_t* bias_i32 = (const int32_t*)bs_buf.data();
    const int32_t* mult_i32 = (const int32_t*)mu_buf.data();
    const int8_t*  shift_i8 = (const int8_t*)sh_buf.data();
    const int8_t*  expected = (const int8_t*)ex_buf.data();

    // ---- Compute output dims
    int OH, OW;
    if (is_transpose) {
        OH = stride_h * (H - 1) + KH - 2 * pad_h + out_pad_h;
        OW = stride_w * (W - 1) + KW - 2 * pad_w + out_pad_w;
    } else {
        OH = (H + 2 * pad_h - KH) / stride_h + 1;
        OW = (W + 2 * pad_w - KW) / stride_w + 1;
    }
    const size_t out_bytes = (size_t)OC * OH * OW;

    if (ex_buf.size() != out_bytes) {
        std::cerr << "ERROR: expected output size " << ex_buf.size()
                  << " != computed " << out_bytes
                  << " (OC=" << OC << " OH=" << OH << " OW=" << OW << ")\n";
        return 2;
    }

    // ---- Run scalar kernel
    std::vector<int8_t> out(out_bytes);
    if (is_transpose) {
        scalar_kernel::conv_transpose2d_scalar(
            in_i8, w_i8, bias_i32, mult_i32, shift_i8, out.data(),
            IC, H, W, OC, KH, KW,
            stride_h, stride_w, pad_h, pad_w,
            out_pad_h, out_pad_w, has_lrelu);
    } else {
        scalar_kernel::conv2d_scalar(
            in_i8, w_i8, bias_i32, mult_i32, shift_i8, out.data(),
            IC, H, W, OC, KH, KW,
            stride_h, stride_w, pad_h, pad_w, has_lrelu);
    }

    // ---- Compare byte-for-byte
    size_t mismatches = 0;
    long long first_mismatch = -1;
    int first_got = 0, first_exp = 0;
    int max_diff = 0;
    long long sum_abs_diff = 0;

    for (size_t i = 0; i < out_bytes; ++i) {
        const int g = out[i];
        const int e = expected[i];
        if (g != e) {
            if (first_mismatch < 0) {
                first_mismatch = (long long)i;
                first_got = g;
                first_exp = e;
            }
            ++mismatches;
            const int d = std::abs(g - e);
            if (d > max_diff) max_diff = d;
            sum_abs_diff += d;
        }
    }

    if (dump_n > 0) {
        std::cerr << "First " << dump_n << " output bytes (got vs expected):\n";
        for (int i = 0; i < dump_n && (size_t)i < out_bytes; ++i) {
            std::cerr << "  [" << i << "] got=" << (int)out[i]
                      << " exp=" << (int)expected[i] << "\n";
        }
    }

    if (mismatches == 0) {
        std::cout << "PASS  (" << out_bytes << " bytes match)" << std::endl;
        return 0;
    }

    const double pct = 100.0 * mismatches / (double)out_bytes;
    const double mean_err = (double)sum_abs_diff / (double)mismatches;
    std::cout << "FAIL  " << mismatches << "/" << out_bytes
              << " (" << pct << "%)"
              << "  first idx=" << first_mismatch
              << " got=" << first_got << " exp=" << first_exp
              << "  max|diff|=" << max_diff
              << "  mean|diff|=" << mean_err
              << std::endl;

    if (verbose) {
        // Convert first_mismatch flat index into (oc, oh, ow)
        const long long pos_in_chan = first_mismatch % (long long)(OH * OW);
        const long long oc_idx = first_mismatch / (long long)(OH * OW);
        const long long oh_idx = pos_in_chan / OW;
        const long long ow_idx = pos_in_chan % OW;
        std::cerr << "  first mismatch at oc=" << oc_idx
                  << " oh=" << oh_idx << " ow=" << ow_idx << "\n";
    }

    return 1;
}
