// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module registration_accumulate_kernel_registration_accumulate_kernel_Pipeline_VITIS_LOOP_141_10 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RFIFONUM,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        read_idx,
        zext_ln140_1,
        p_reload88,
        p_reload87,
        p_reload86,
        p_reload85,
        p_reload84,
        p_reload83,
        p_reload82,
        p_reload81,
        p_reload80,
        p_reload79,
        p_reload78,
        p_reload77,
        p_reload76,
        p_reload75,
        p_reload74,
        p_reload73,
        p_reload72,
        p_reload71,
        p_reload70,
        p_reload69,
        p_reload,
        empty,
        jtj_out,
        zext_ln140
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [63:0] m_axi_gmem3_AWADDR;
output  [0:0] m_axi_gmem3_AWID;
output  [31:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [0:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [63:0] m_axi_gmem3_WDATA;
output  [7:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [0:0] m_axi_gmem3_WID;
output  [0:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [63:0] m_axi_gmem3_ARADDR;
output  [0:0] m_axi_gmem3_ARID;
output  [31:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [0:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [63:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [0:0] m_axi_gmem3_RID;
input  [8:0] m_axi_gmem3_RFIFONUM;
input  [0:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [0:0] m_axi_gmem3_BID;
input  [0:0] m_axi_gmem3_BUSER;
input  [5:0] read_idx;
input  [2:0] zext_ln140_1;
input  [63:0] p_reload88;
input  [63:0] p_reload87;
input  [63:0] p_reload86;
input  [63:0] p_reload85;
input  [63:0] p_reload84;
input  [63:0] p_reload83;
input  [63:0] p_reload82;
input  [63:0] p_reload81;
input  [63:0] p_reload80;
input  [63:0] p_reload79;
input  [63:0] p_reload78;
input  [63:0] p_reload77;
input  [63:0] p_reload76;
input  [63:0] p_reload75;
input  [63:0] p_reload74;
input  [63:0] p_reload73;
input  [63:0] p_reload72;
input  [63:0] p_reload71;
input  [63:0] p_reload70;
input  [63:0] p_reload69;
input  [63:0] p_reload;
input  [4:0] empty;
input  [63:0] jtj_out;
input  [2:0] zext_ln140;

reg ap_idle;
reg m_axi_gmem3_AWVALID;
reg[63:0] m_axi_gmem3_AWADDR;
reg m_axi_gmem3_WVALID;
reg[63:0] m_axi_gmem3_WDATA;
reg m_axi_gmem3_BREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln141_reg_678;
reg    ap_block_state2_io;
reg   [0:0] icmp_ln145_reg_692;
reg   [0:0] icmp_ln145_reg_692_pp0_iter1_reg;
reg    ap_block_state4_io;
reg    ap_block_state8_pp0_stage1_iter3;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem3_blk_n_AW;
wire    ap_block_pp0_stage1;
reg    gmem3_blk_n_W;
wire    ap_block_pp0_stage0;
reg    gmem3_blk_n_B;
reg   [0:0] icmp_ln145_reg_692_pp0_iter3_reg;
reg    ap_block_state3_io;
reg    ap_block_state9_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
wire   [6:0] zext_ln140_cast_fu_372_p1;
reg   [6:0] zext_ln140_cast_reg_667;
reg   [3:0] c_1_reg_672;
wire   [0:0] icmp_ln141_fu_397_p2;
reg   [0:0] icmp_ln141_reg_678_pp0_iter1_reg;
reg   [0:0] icmp_ln141_reg_678_pp0_iter2_reg;
wire   [63:0] val_fu_420_p45;
reg   [63:0] val_reg_682;
reg   [60:0] trunc_ln7_reg_687;
wire   [0:0] icmp_ln145_fu_546_p2;
reg   [0:0] icmp_ln145_reg_692_pp0_iter2_reg;
reg    ap_block_pp0_stage1_11001;
reg   [60:0] trunc_ln8_reg_702;
wire   [63:0] bitcast_ln144_fu_634_p1;
reg   [63:0] bitcast_ln144_reg_707;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
wire  signed [63:0] sext_ln144_fu_568_p1;
wire  signed [63:0] sext_ln146_fu_638_p1;
reg    ap_block_pp0_stage0_01001;
reg    ap_block_pp0_stage1_01001;
reg   [3:0] c_fu_176;
wire   [3:0] zext_ln140_1_cast_fu_380_p1;
wire   [3:0] add_ln141_fu_552_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_c_1;
reg   [5:0] read_idx_1_fu_180;
wire   [5:0] add_ln143_fu_414_p2;
reg   [5:0] ap_sig_allocacmp_read_idx_1_load;
wire   [63:0] val_fu_420_p43;
wire   [4:0] val_fu_420_p44;
wire   [5:0] zext_ln141_fu_406_p1;
wire   [5:0] p_cast_fu_376_p1;
wire   [5:0] add_ln144_fu_512_p2;
wire   [8:0] shl_ln_fu_518_p3;
wire   [63:0] zext_ln144_fu_526_p1;
wire   [63:0] add_ln144_1_fu_530_p2;
wire   [4:0] tmp_1_fu_585_p3;
wire   [6:0] p_shl_fu_578_p3;
wire   [6:0] zext_ln146_1_fu_592_p1;
wire   [6:0] sub_ln146_fu_596_p2;
wire   [6:0] add_ln146_fu_602_p2;
wire   [9:0] shl_ln1_fu_607_p3;
wire   [63:0] zext_ln146_fu_615_p1;
wire   [63:0] add_ln146_1_fu_619_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter3_stage0;
reg    ap_idle_pp0_0to2;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_1to4;
reg    ap_done_pending_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_547;
wire   [4:0] val_fu_420_p1;
wire   [4:0] val_fu_420_p3;
wire   [4:0] val_fu_420_p5;
wire   [4:0] val_fu_420_p7;
wire   [4:0] val_fu_420_p9;
wire   [4:0] val_fu_420_p11;
wire   [4:0] val_fu_420_p13;
wire   [4:0] val_fu_420_p15;
wire   [4:0] val_fu_420_p17;
wire   [4:0] val_fu_420_p19;
wire   [4:0] val_fu_420_p21;
wire   [4:0] val_fu_420_p23;
wire   [4:0] val_fu_420_p25;
wire   [4:0] val_fu_420_p27;
wire   [4:0] val_fu_420_p29;
wire   [4:0] val_fu_420_p31;
wire  signed [4:0] val_fu_420_p33;
wire  signed [4:0] val_fu_420_p35;
wire  signed [4:0] val_fu_420_p37;
wire  signed [4:0] val_fu_420_p39;
wire  signed [4:0] val_fu_420_p41;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 c_fu_176 = 4'd0;
#0 read_idx_1_fu_180 = 6'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) registration_accumulate_kernel_sparsemux_43_5_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 64 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 64 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 64 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 64 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 64 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 64 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 64 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 64 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 64 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 64 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 64 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 64 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 64 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 64 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 64 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 64 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 64 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 64 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 64 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 64 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 64 ),
    .def_WIDTH( 64 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 64 ))
sparsemux_43_5_64_1_1_U67(
    .din0(p_reload88),
    .din1(p_reload87),
    .din2(p_reload86),
    .din3(p_reload85),
    .din4(p_reload84),
    .din5(p_reload83),
    .din6(p_reload82),
    .din7(p_reload81),
    .din8(p_reload80),
    .din9(p_reload79),
    .din10(p_reload78),
    .din11(p_reload77),
    .din12(p_reload76),
    .din13(p_reload75),
    .din14(p_reload74),
    .din15(p_reload73),
    .din16(p_reload72),
    .din17(p_reload71),
    .din18(p_reload70),
    .din19(p_reload69),
    .din20(p_reload),
    .def(val_fu_420_p43),
    .sel(val_fu_420_p44),
    .dout(val_fu_420_p45)
);

registration_accumulate_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln141_fu_397_p2 == 1'd0))) begin
            c_fu_176 <= add_ln141_fu_552_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_176 <= zext_ln140_1_cast_fu_380_p1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln141_fu_397_p2 == 1'd0))) begin
            read_idx_1_fu_180 <= add_ln143_fu_414_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            read_idx_1_fu_180 <= read_idx;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        bitcast_ln144_reg_707 <= bitcast_ln144_fu_634_p1;
        c_1_reg_672 <= ap_sig_allocacmp_c_1;
        icmp_ln141_reg_678 <= icmp_ln141_fu_397_p2;
        icmp_ln141_reg_678_pp0_iter1_reg <= icmp_ln141_reg_678;
        icmp_ln141_reg_678_pp0_iter2_reg <= icmp_ln141_reg_678_pp0_iter1_reg;
        icmp_ln145_reg_692 <= icmp_ln145_fu_546_p2;
        icmp_ln145_reg_692_pp0_iter1_reg <= icmp_ln145_reg_692;
        icmp_ln145_reg_692_pp0_iter2_reg <= icmp_ln145_reg_692_pp0_iter1_reg;
        icmp_ln145_reg_692_pp0_iter3_reg <= icmp_ln145_reg_692_pp0_iter2_reg;
        trunc_ln7_reg_687 <= {{add_ln144_1_fu_530_p2[63:3]}};
        val_reg_682 <= val_fu_420_p45;
        zext_ln140_cast_reg_667[2 : 0] <= zext_ln140_cast_fu_372_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        trunc_ln8_reg_702 <= {{add_ln146_1_fu_619_p2[63:3]}};
    end
end

always @ (*) begin
    if (((icmp_ln141_reg_678 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln141_reg_678_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter3_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready_pp0_iter3_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (ap_loop_exit_ready == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_c_1 = zext_ln140_1_cast_fu_380_p1;
    end else begin
        ap_sig_allocacmp_c_1 = c_fu_176;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_read_idx_1_load = read_idx;
    end else begin
        ap_sig_allocacmp_read_idx_1_load = read_idx_1_fu_180;
    end
end

always @ (*) begin
    if ((((icmp_ln141_reg_678 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln145_reg_692 == 1'd0)))) begin
        gmem3_blk_n_AW = m_axi_gmem3_AWREADY;
    end else begin
        gmem3_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln145_reg_692_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)))) begin
        gmem3_blk_n_B = m_axi_gmem3_BVALID;
    end else begin
        gmem3_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (icmp_ln145_reg_692_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0)))) begin
        gmem3_blk_n_W = m_axi_gmem3_WREADY;
    end else begin
        gmem3_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln145_reg_692 == 1'd0))) begin
        m_axi_gmem3_AWADDR = sext_ln146_fu_638_p1;
    end else if (((icmp_ln141_reg_678 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem3_AWADDR = sext_ln144_fu_568_p1;
    end else begin
        m_axi_gmem3_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln141_reg_678 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln145_reg_692 == 1'd0)))) begin
        m_axi_gmem3_AWVALID = 1'b1;
    end else begin
        m_axi_gmem3_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln145_reg_692_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        m_axi_gmem3_BREADY = 1'b1;
    end else begin
        m_axi_gmem3_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if ((1'b1 == ap_condition_547)) begin
            m_axi_gmem3_WDATA = bitcast_ln144_reg_707;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
            m_axi_gmem3_WDATA = bitcast_ln144_fu_634_p1;
        end else begin
            m_axi_gmem3_WDATA = 'bx;
        end
    end else begin
        m_axi_gmem3_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln145_reg_692_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        m_axi_gmem3_WVALID = 1'b1;
    end else begin
        m_axi_gmem3_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to2 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter3_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln141_fu_552_p2 = (ap_sig_allocacmp_c_1 + 4'd1);

assign add_ln143_fu_414_p2 = (ap_sig_allocacmp_read_idx_1_load + 6'd1);

assign add_ln144_1_fu_530_p2 = (zext_ln144_fu_526_p1 + jtj_out);

assign add_ln144_fu_512_p2 = (zext_ln141_fu_406_p1 + p_cast_fu_376_p1);

assign add_ln146_1_fu_619_p2 = (zext_ln146_fu_615_p1 + jtj_out);

assign add_ln146_fu_602_p2 = (sub_ln146_fu_596_p2 + zext_ln140_cast_reg_667);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter4));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter4)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage1_iter3));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage1_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state8_pp0_stage1_iter3)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln141_reg_678 == 1'd0) & (m_axi_gmem3_AWREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((m_axi_gmem3_WREADY == 1'b0) | ((m_axi_gmem3_AWREADY == 1'b0) & (icmp_ln145_reg_692 == 1'd0)));
end

always @ (*) begin
    ap_block_state4_io = ((m_axi_gmem3_WREADY == 1'b0) & (icmp_ln145_reg_692_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_block_state8_pp0_stage1_iter3 = (m_axi_gmem3_BVALID == 1'b0);
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter4 = ((m_axi_gmem3_BVALID == 1'b0) & (icmp_ln145_reg_692_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_condition_547 = ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001) & (icmp_ln145_reg_692_pp0_iter1_reg == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign bitcast_ln144_fu_634_p1 = val_reg_682;

assign icmp_ln141_fu_397_p2 = ((ap_sig_allocacmp_c_1 == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln145_fu_546_p2 = ((zext_ln140_1_cast_fu_380_p1 == ap_sig_allocacmp_c_1) ? 1'b1 : 1'b0);

assign m_axi_gmem3_ARADDR = 64'd0;

assign m_axi_gmem3_ARBURST = 2'd0;

assign m_axi_gmem3_ARCACHE = 4'd0;

assign m_axi_gmem3_ARID = 1'd0;

assign m_axi_gmem3_ARLEN = 32'd0;

assign m_axi_gmem3_ARLOCK = 2'd0;

assign m_axi_gmem3_ARPROT = 3'd0;

assign m_axi_gmem3_ARQOS = 4'd0;

assign m_axi_gmem3_ARREGION = 4'd0;

assign m_axi_gmem3_ARSIZE = 3'd0;

assign m_axi_gmem3_ARUSER = 1'd0;

assign m_axi_gmem3_ARVALID = 1'b0;

assign m_axi_gmem3_AWBURST = 2'd0;

assign m_axi_gmem3_AWCACHE = 4'd0;

assign m_axi_gmem3_AWID = 1'd0;

assign m_axi_gmem3_AWLEN = 64'd1;

assign m_axi_gmem3_AWLOCK = 2'd0;

assign m_axi_gmem3_AWPROT = 3'd0;

assign m_axi_gmem3_AWQOS = 4'd0;

assign m_axi_gmem3_AWREGION = 4'd0;

assign m_axi_gmem3_AWSIZE = 3'd0;

assign m_axi_gmem3_AWUSER = 1'd0;

assign m_axi_gmem3_RREADY = 1'b0;

assign m_axi_gmem3_WID = 1'd0;

assign m_axi_gmem3_WLAST = 1'b0;

assign m_axi_gmem3_WSTRB = 8'd255;

assign m_axi_gmem3_WUSER = 1'd0;

assign p_cast_fu_376_p1 = empty;

assign p_shl_fu_578_p3 = {{c_1_reg_672}, {3'd0}};

assign sext_ln144_fu_568_p1 = $signed(trunc_ln7_reg_687);

assign sext_ln146_fu_638_p1 = $signed(trunc_ln8_reg_702);

assign shl_ln1_fu_607_p3 = {{add_ln146_fu_602_p2}, {3'd0}};

assign shl_ln_fu_518_p3 = {{add_ln144_fu_512_p2}, {3'd0}};

assign sub_ln146_fu_596_p2 = (p_shl_fu_578_p3 - zext_ln146_1_fu_592_p1);

assign tmp_1_fu_585_p3 = {{c_1_reg_672}, {1'd0}};

assign val_fu_420_p43 = 'bx;

assign val_fu_420_p44 = ap_sig_allocacmp_read_idx_1_load[4:0];

assign zext_ln140_1_cast_fu_380_p1 = zext_ln140_1;

assign zext_ln140_cast_fu_372_p1 = zext_ln140;

assign zext_ln141_fu_406_p1 = ap_sig_allocacmp_c_1;

assign zext_ln144_fu_526_p1 = shl_ln_fu_518_p3;

assign zext_ln146_1_fu_592_p1 = tmp_1_fu_585_p3;

assign zext_ln146_fu_615_p1 = shl_ln1_fu_607_p3;

always @ (posedge ap_clk) begin
    zext_ln140_cast_reg_667[6:3] <= 4'b0000;
end

endmodule //registration_accumulate_kernel_registration_accumulate_kernel_Pipeline_VITIS_LOOP_141_10
